version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '4000:4000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/templatehub
      - JWT_SECRET=replace_this
    volumes:
      - ./server/uploads:/usr/src/app/../uploads
    depends_on:
      - mongo

  frontend:
    build:
      context: ./public
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    restart: unless-stopped

volumes:
  mongo-data:
